# Generated by Django 5.1.2 on 2024-10-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_productentry_id_alter_productorder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_hp', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
            ],
        ),
    ]
