# Generated by Django 5.1.1 on 2024-10-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('food_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('shop_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rating_default', models.DecimalField(decimal_places=1, max_digits=5)),
                ('food_desc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProductEntry',
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
