# Generated by Django 5.1 on 2024-12-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0006_delete_komentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
