# Generated by Django 5.1.1 on 2024-12-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0007_favorite_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='note',
            field=models.TextField(blank=True, default='.'),
        ),
    ]
